[build]
  functions = "netlify/functions"
  publish = "public"
  
[functions]
  node_bundler = "esbuild"
  
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Accept, Authorization"
    Cache-Control = "s-maxage=300, stale-while-revalidate"

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# Endpoints pour l'application web (architecture simplifiée)
[[redirects]]
  from = "/api/marques"
  to = "/.netlify/functions/marques"
  status = 200

[[redirects]]
  from = "/api/evenements"
  to = "/.netlify/functions/evenements"
  status = 200

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/categories"
  status = 200

[[redirects]]
  from = "/api/secteurs-marque"
  to = "/.netlify/functions/secteurs-marque"
  status = 200

[[redirects]]
  from = "/api/beneficiaires/chaine"
  to = "/.netlify/functions/beneficiaires-chaine"
  status = 200

# Fallbacks et monitoring
[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/health"
  status = 200