[build]
  functions = "netlify/functions"
  publish = "public"
  
[functions]
  node_bundler = "esbuild"
  
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Accept, Authorization"
    Cache-Control = "s-maxage=300, stale-while-revalidate"

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
  
[[redirects]]
  from = "/api/brands/version"
  to = "/.netlify/functions/brands-version"
  status = 200

[[redirects]]
  from = "/api/brands/updates"
  to = "/.netlify/functions/brands-updates"
  status = 200

[[redirects]]
  from = "/api/brands/full"
  to = "/.netlify/functions/brands-full"
  status = 200

[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/health"
  status = 200